version: '3.8'
services: 
    mywebcontainer: 
      container_name: nginx_web 
      build: .
      ports: 
        - 8080:80

    newwebcontainer: 
      container_name: httpd_web
      image: httpd:latest
      ports:
        - 8089:80